name = "bingo-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "bingo-api"

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"
script_name = "bingo-api"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]
