name = "bingo-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
UPSTASH_REDIS_REST_URL = "https://smiling-whippet-27638.upstash.io"
UPSTASH_REDIS_REST_TOKEN = "AWv2AAIncDFmODU2NWE4YzRlYWE0MDQ1YjAxMGZlMTgzM2E5MTUyZXAxMjc2Mzg"
BOT_TOKEN = "8214698066:AAFVjf2wjI1KcxXq0jKYXcjNyIYEMmiXvYE"

[env.production]
name = "bingo-api"

[[durable_objects.bindings]]
name = "GAME_ROOM"
class_name = "GameRoom"
script_name = "bingo-api"

[[durable_objects.bindings]]
name = "PLAYER_TRACKER"
class_name = "PlayerTracker"
script_name = "bingo-api"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["PlayerTracker"]
